Repository HS-Advanced-Mobile-Programming/overture, pull requests merged in 2024-12, with the labels that each got.

#3 [HAJ-1] : Add SettingScreen
  .gitignore
  lib/ProfileScreen.dart
  lib/ProfileScreen/AccountSettingScreen.dart
  lib/ProfileScreen/PrivacyPolicyScreen.dart
  lib/ProfileScreen/SettingScreen.dart
  lib/ProfileScreen/TermScreen.dart
  lib/main.dart
Labels: enhancement

#4 [HAJ-2] : Implement search bar, review display, and AI-based review summarization
  lib/ProfileScreen/SettingScreen.dart
  lib/SearchScreen/PlaceDetailsModal.dart
  lib/SearchScreen/SearchScreen.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#10 Feature/search screen
  lib/SearchScreen/PlaceDetailsModal.dart
  lib/SearchScreen/SearchScreen.dart
  lib/email_login.dart
  lib/email_signup.dart
  lib/email_verification.dart
  lib/main_screen.dart
Labels: enhancement

#11 OCR Feature Complete
  lib/CheckListScreen/CheckListScreen.dart
  lib/MenuTranslationScreen/DeepLTranslate.dart
  lib/MenuTranslationScreen/MenuTranslationScreen.dart
  lib/main.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#12 일정 관리 API 연동
  android/app/build.gradle
  android/build.gradle
  lib/ScheduleScreen.dart
  lib/main.dart
  lib/models/schedule_model_files/schedule_model.dart
  lib/screens/schedule_view.dart
  lib/service/FirestoreScheduleService.dart
  lib/service/ScheduleDto.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement, ui

#14 HomeScreen MyScheduleWidget Complete
  lib/HomeScreen/HomeScreenBody.dart
  lib/HomeScreen/MyScheduleWidget.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: ui

#15 스케줄 위치 검색 및 좌표 데이터 추가
  lib/main.dart
  lib/models/place_model_files/place_model.dart
  lib/models/schedule_model_files/schedule_model.dart
  lib/service/ScheduleDto.dart
  lib/widgets/place_repository.dart
  lib/widgets/place_search.dart
  lib/widgets/schedule_form.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#16 위치 API 리스트 크기 증량
  lib/widgets/place_repository.dart
Labels: enhancement

#17 Checklist Clothes Add, Delete, Update Complete
  android/settings.gradle
  lib/CheckListScreen/CheckListScreen.dart
  lib/CheckListScreen/ClothExpansionTileWidget.dart
  lib/CheckListScreen/ClothingChecklistItemWidget.dart
  lib/CheckListScreen/ClothingChecklistWidget.dart
  lib/CheckListScreen/EssentialCheckListWidget.dart
  lib/home_screen.dart
  lib/main.dart
  lib/models/check_model_files/airportinfo_model.dart
  lib/models/check_model_files/clothes_model.dart
  lib/models/check_model_files/essential_model.dart
  lib/service/FirestoreAirportinfoService.dart
Labels: enhancement
